"""Public, illustrative product-system views paired with actual portfolio evidence."""
from html import escape as e

def icon(name):
 return f'<img src="images/technology/{name}.svg" alt="" width="32" height="32" loading="lazy">'

def closing_sections():
 return '''<section id="approach" class="system-section" data-section-reveal><div class="system-inner"><div class="system-heading"><div><p class="studio-byline">AI, applied to your business</p><h2>Connect the knowledge.<br>Put it to work.</h2></div><p>Your information, tools and everyday workflows—connected through software built around the way your business operates.</p></div>
 <div class="system-diagram" aria-label="Connect business knowledge, automate workflows, and explore results">
 <article class="system-stage"><div class="stage-art context-art" aria-hidden="true"><div class="source-sheet sheet-back"><span>Business systems</span><i></i><i></i><i></i></div><div class="source-sheet sheet-front"><b>Documents · Reports · Data</b><i></i><i></i><div class="source-tags"><span>Connected context</span><span>AI-ready</span></div></div></div><div class="stage-heading"><span>01 / Knowledge</span><b>AI that knows your business.</b><p>Connect scattered documents and systems so AI can answer questions with the right context.</p></div></article>
 <div class="system-connector" aria-hidden="true"><i></i><span>→</span></div>
 <article class="system-stage"><div class="stage-art logic-art" aria-hidden="true"><div class="logic-orbit orbit-outer"></div><div class="logic-orbit orbit-inner"></div><span class="logic-satellite satellite-data">On a schedule</span><span class="logic-satellite satellite-tools">Your tools</span><div class="logic-core"><img src="images/capabilities/workflow.svg" width="40" height="40" alt=""></div><span class="logic-satellite satellite-review">Human checkpoints</span></div><div class="stage-heading"><span>02 / Automation</span><b>Less repetitive work.</b><p>Give AI the tools to carry out repeatable tasks, with scheduled routines and human checkpoints.</p></div></article>
 <div class="system-connector" aria-hidden="true"><i></i><span>→</span></div>
 <article class="system-stage"><div class="stage-art insight-art" aria-hidden="true"><div class="insight-window"><div class="insight-top"><span>Business overview</span><i></i></div><div class="insight-chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="insight-chat"><span>What changed this week?</span><b>↗</b></div></div></div><div class="stage-heading"><span>03 / Visibility</span><b>Answers you can explore.</b><p>See trends in a custom dashboard. Ask questions and shape what gets tracked through conversation.</p></div></article>
 </div><div class="system-baseline"><span>From a focused workflow to a connected platform.</span><a href="mailto:baylor@manifoldengineering.ai">Let’s talk about your workflow <span aria-hidden="true">↗</span></a></div></div></section>
 <section class="about-section illustrated-about" id="about"><div class="about-narrative"><p class="studio-byline">The person behind the work</p><h2>An engineer’s curiosity.<br>A builder’s perspective.</h2><div class="about-copy"><p>I’m Baylor, founder of Manifold Engineering. I turn business problems into useful AI and software—from the first idea to the interface people use.</p><p>I build across the stack, and build tools that make the engineering process clearer, too.</p><div class="about-links"><a class="text-link" href="resume.html">Background & experience ↗</a><a class="text-link" href="https://www.linkedin.com/in/baylor-harrison">LinkedIn ↗</a></div></div></div>
 <div class="toolkit" data-section-reveal><div class="toolkit-grid" aria-hidden="true"></div><div class="toolkit-heading"><span>The craft behind the products</span><b>Built end to end.</b></div><div class="toolkit-layers">
 <a class="tool-layer interface-layer" href="alpha-seo.html"><div class="tool-icons">'''+icon('react')+icon('typescript')+'''</div><div><span>Interfaces</span><b>React + TypeScript</b><p>Web applications and product workflows</p></div><em aria-hidden="true">↗</em></a>
 <a class="tool-layer service-layer" href="till.html"><div class="tool-icons">'''+icon('python')+icon('nodejs')+'''</div><div><span>Services</span><b>Python + Node.js</b><p>Data processing, APIs and integrations</p></div><em aria-hidden="true">↗</em></a>
 <a class="tool-layer cloud-layer" href="fiftyflowers.html"><div class="tool-icons">'''+icon('firebase')+'''</div><div><span>Cloud & data</span><b>Firebase + Google Cloud</b><p>Connected applications and shared data</p></div><em aria-hidden="true">↗</em></a>
 </div><a class="toolkit-mobile" href="ai-travel-companion.html">'''+icon('swift')+'''<span>Also built for the small screen.<b>Explore the Swift travel app ↗</b></span></a><p class="toolkit-caption">Selected technologies used across the work.</p></div></section>'''


def capability_strip():
 items=[('brain-circuit','AI applications'),('layers','Full-stack products'),('cloud-cog','Cloud integrations'),('workflow','Engineering tools')]
 return '<div class="studio-disciplines">'+''.join(f'<span><img src="images/capabilities/{name}.svg" alt="" width="24" height="24">{label}</span>' for name,label in items)+'</div>'
