"""Public, illustrative product-system views paired with actual portfolio evidence."""
from html import escape as e

def icon(name):
 return f'<img src="images/technology/{name}.svg" alt="" width="32" height="32" loading="lazy">'

def closing_sections():
 return '''<section id="approach" class="system-section" data-section-reveal><div class="system-inner"><div class="system-heading"><div><p class="studio-byline">Built around people</p><h2>Less friction.<br>More possibility.</h2></div><p>From helping a customer to understanding a report. Software with a clear job to do.</p></div>
 <div class="system-diagram" aria-label="Three examples of useful software: customer support, connected scoring and report analysis">
 <a class="system-stage" href="fiftyflowers.html"><div class="stage-art context-art" aria-hidden="true"><div class="source-sheet sheet-back"><span>Reviews · Claims</span><i></i><i></i><i></i></div><div class="source-sheet sheet-front"><b>Questions · Disputes</b><i></i><i></i><div class="source-tags"><span>Shared context</span><span>One workspace</span></div></div></div><div class="stage-heading"><span>01 / Support</span><b>Help across the customer journey.</b><p>Four support apps share conversation and case history.</p><em>See FiftyFlowers ↗</em></div></a>
 <div class="system-connector" aria-hidden="true"><i></i></div>
 <a class="system-stage" href="till.html"><div class="stage-art logic-art" aria-hidden="true"><div class="logic-orbit orbit-outer"></div><div class="logic-orbit orbit-inner"></div><span class="logic-satellite satellite-data">Data</span><span class="logic-satellite satellite-tools">Tools</span><div class="logic-core"><svg viewBox="0 0 48 48" fill="none"><path d="M16 9 5 24l11 15M32 9l11 15-11 15M28 5 20 43" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></div><span class="logic-satellite satellite-review">Review</span></div><div class="stage-heading"><span>02 / Decisions</span><b>Score inside the lending workflow.</b><p>Application data in. A scoring result back where it’s needed.</p><em>See Till ↗</em></div></a>
 <div class="system-connector" aria-hidden="true"><i></i></div>
 <a class="system-stage" href="create-spaces.html"><div class="stage-art workspace-art"><div class="workspace-window"><div class="workspace-chrome" aria-hidden="true"><i></i><i></i><i></i><span>Reporting workspace</span></div><img src="images/product-screens/create-spaces-01-overview.webp" width="1440" height="900" alt="Create Spaces reporting dashboard with confidential values redacted" loading="lazy"></div><span class="workspace-note">Earlier local reporting view</span></div><div class="stage-heading"><span>03 / Insight</span><b>Ask a question. See the source.</b><p>The local reporting workspace now pairs AI answers with cited report pages.</p><em>See Create Spaces ↗</em></div></a>
 </div><div class="system-baseline"><span>Three separate products. Purpose-built around the work.</span><a href="engineering-platform.html">The tools behind the process <span aria-hidden="true">↗</span></a></div></div></section>
 <section class="about-section illustrated-about" id="about"><div class="about-narrative"><p class="studio-byline">The person behind the work</p><h2>An engineer’s curiosity.<br>A builder’s perspective.</h2><div class="about-copy"><p>I’m Baylor, founder of Manifold Engineering. I turn business problems into useful AI and software—from the first idea to the interface people use.</p><p>I build across the stack, and build tools that make the engineering process clearer, too.</p><div class="about-links"><a class="text-link" href="resume.html">Background & experience ↗</a><a class="text-link" href="https://www.linkedin.com/in/baylor-harrison">LinkedIn ↗</a></div></div></div>
 <div class="toolkit" data-section-reveal><div class="toolkit-grid" aria-hidden="true"></div><div class="toolkit-heading"><span>The craft behind the products</span><b>Built end to end.</b></div><div class="toolkit-layers">
 <a class="tool-layer interface-layer" href="alpha-seo.html"><div class="tool-icons">'''+icon('react')+icon('typescript')+'''</div><div><span>Interfaces</span><b>React + TypeScript</b><p>Web applications and product workflows</p></div><em aria-hidden="true">↗</em></a>
 <a class="tool-layer service-layer" href="till.html"><div class="tool-icons">'''+icon('python')+icon('nodejs')+'''</div><div><span>Services</span><b>Python + Node.js</b><p>Data processing, APIs and integrations</p></div><em aria-hidden="true">↗</em></a>
 <a class="tool-layer cloud-layer" href="fiftyflowers.html"><div class="tool-icons">'''+icon('firebase')+'''</div><div><span>Cloud & data</span><b>Firebase + Google Cloud</b><p>Connected applications and shared data</p></div><em aria-hidden="true">↗</em></a>
 </div><a class="toolkit-mobile" href="ai-travel-companion.html">'''+icon('swift')+'''<span>Also built for the small screen.<b>Explore the Swift travel app ↗</b></span></a><p class="toolkit-caption">Selected technologies used across the work.</p></div></section>'''
