"""Editorial homepage composition; existing case-study content stays in the shared builder."""
from html import escape as e
from atmosphere import stream

def homepage(projects, visual, card, brand_art):
 hero='''<section class="studio-hero"><div class="studio-intro"><p class="studio-byline">Baylor Harrison · Manifold Engineering</p><h1>Useful AI.<br>Thoughtfully<br>engineered.</h1><p class="studio-deck">I turn business information, everyday workflows and ambitious ideas into software people can actually use.</p><div class="hero-actions"><a class="button dark" href="#selected-work">Explore selected work <span aria-hidden="true">↓</span></a><a class="text-link" href="#about">Meet the engineer</a></div><p class="studio-location">Independent engineer & founder <span>Based in Arizona</span></p></div>'''+stream(projects)+'''</section><div class="studio-disciplines"><span>AI applications</span><span>Full-stack products</span><span>Cloud integrations</span><span>Engineering tools</span></div>'''
 stories={
 'fiftyflowers':('AI, woven into everyday work.','An internal platform brings support, marketing and company knowledge together. A collection of practical tools, designed around how each team works.','A connected platform','Production tools alongside ongoing development'),
 'till':('Better decisions. Less overhead.','Machine-learning scoring and a lending dashboard turn application data into information the team can act on.','Business impact','$24,000 annualized savings'),
 'engineering-platform':('Better tools for building better tools.','The Record, Brain and Jarvis OS connect project scope, durable knowledge and supervised engineering workflows.','An evolving toolkit','Working tools with an orchestration prototype')}
 featured='<section id="selected-work" class="selected-work"><div class="selected-heading"><p class="studio-byline">Selected work</p><h2 data-reveal-heading>Built around<br>the real problem.</h2><p>A few ways that takes shape.</p></div>'
 for pid,(title,desc,label,result) in stories.items():
  p=next(p for p in projects if p['id']==pid)
  mark=brand_art(p,"featured-brand") or f'<span class="featured-name">{e(p["name"])}</span>'
  featured+=f'''<article class="featured-story" data-featured="{pid}"><div class="featured-copy">{mark}<p class="featured-sector">{e(p['sector'])}</p><h3>{e(title)}</h3><p>{e(desc)}</p><div class="featured-result"><span>{e(label)}</span><strong>{e(result)}</strong></div><a class="text-link" href="{pid}.html">Explore {e(p['name'])} <span aria-hidden="true">↗</span></a></div><div class="featured-stage"><div class="featured-media">{visual(p,layered=True)}</div></div></article>'''
 featured+='</section>'
 directory='''<section class="work-section directory-section" id="work"><div class="section-heading"><div><p class="studio-byline">The complete collection</p><h2>More to explore.</h2></div><p>Client products, engineering tools<br>and the projects that came before.</p></div><div class="work-toolbar"><div class="filters" role="group" aria-label="Filter projects" hidden><button type="button" data-filter="all" aria-pressed="true">All work <span>13</span></button><button type="button" data-filter="business" aria-pressed="false">Business systems</button><button type="button" data-filter="engineering" aria-pressed="false">Developer & research tools</button><button type="button" data-filter="earlier" aria-pressed="false">Earlier work</button></div><span class="project-count" role="status" aria-live="polite">13 projects</span></div><div class="project-grid">'''+''.join(card(p,n) for n,p in enumerate(projects,1))+'</div></section>'
 about='''<section class="approach-section" id="approach"><div class="section-heading"><div><p class="studio-byline">How I approach the work</p><h2 data-reveal-heading>Make it useful.<br>Then make it hold up.</h2></div><p>Good software starts with the operation and stays grounded in the people using it.</p></div><div class="approach-grid"><article><span>01</span><h3>Understand the work.</h3><p>Find the information, decisions and repetitive steps that matter. Shape the scope around the actual business need.</p></article><article><span>02</span><h3>Connect the pieces.</h3><p>Bring the interface, existing tools and cloud services together into an application people can use.</p></article><article><span>03</span><h3>Prove the useful part.</h3><p>Test the behavior, make limitations visible and leave clear evidence and handoffs for whatever comes next.</p></article></div></section><section class="about-section" id="about"><div><p class="studio-byline">The person behind the work</p><h2 data-reveal-heading>An engineer’s curiosity.<br>A builder’s perspective.</h2></div><div class="about-copy"><p>I’m the founder of Manifold Engineering, an AI development studio. My work brings together product thinking, full-stack applications, integrations and cloud infrastructure.</p><p>I’m interested in the space between what a business does today and what better tools could make possible—from a more useful dashboard to a connected workflow that takes repetitive work off someone’s plate.</p><p>I also build tools for the engineering process itself, so project knowledge, focused assignments and evidence stay connected as the work evolves.</p><div class="about-links"><a class="text-link" href="resume.html">Background & experience</a><a class="text-link" href="https://www.linkedin.com/in/baylor-harrison">LinkedIn ↗</a></div></div></section>'''
 return hero+featured+directory+about
